pgrank: PageRank Class Reference
PageRank Class Reference
PageRank class (for computing pagerank)
#include <pagerank.hpp>
Public Member Functions
PageRank (const arma::sp_mat &, const bool &=false, const double &=ALPHA)
Constructor of PageRank object from adjacency matrix.
PageRank (const std::pair< arma::sp_mat, arma::rowvec > &, const double &=ALPHA)
Constructor of PageRank object from normal adjacency matrix and dangling nodes vector.
PageRank (const char *, const bool &=false, const double &=ALPHA, const char *="objects", const char *="url", const char *="urls")
Constructor of PageRank object from json.
~PageRank ()
Default nil destroyer.
void setAlpha (const double &alpha)
Set dumping factor (_alpha)
double getAlpha ()
Get current dumping factor.
arma::sp_mat getAdjMatrix ()
Get arma adjacency matrix.
arma::vec getDangVec ()
Get arma dangling nodes vector.
arma::vec getRank ()
Get arma rank result vector.
void csvRank (const char *, const bool &=false)
Write to csv rank result vector (_rank)
void evoRank (const double &=EPSILON, const bool &=false)
Evolve pagerank of _am with _alpha, and store result in _rank.
void evoRank (const double &, const double &=EPSILON, const bool &=false)
Evolve pagerank of _sm with _alpha, and store result in _rank.
Detailed Description
PageRank class (for computing pagerank)
Definition at line 25 of file pagerank.hpp.
Constructor & Destructor Documentation
PageRank() [1/3]
PageRank::PageRank (const arma::sp_mat & am, const bool & info = false, const double & alpha = ALPHA)
Constructor of PageRank object from adjacency matrix.
Parameters
am Armadillo spare adjacency matrix
info Stdout informations, default: false
alpha Dumping factor, default: ALPHA
Authors
Andrea Rossoni
Version
0.1.2
Definition at line 10 of file pagerank.cpp.
References setAlpha().
PageRank() [2/3]
PageRank::PageRank (const std::pair< arma::sp_mat, arma::rowvec > & pr, const double & alpha = ALPHA)
Constructor of PageRank object from normal adjacency matrix and dangling nodes vector.
Parameters
pr Pair armadillo spare adjacency matrixa and dangling vector
alpha Dumping factor, default: ALPHA
Definition at line 47 of file pagerank.cpp.
References setAlpha().
PageRank() [3/3]
PageRank::PageRank (const char * json_path, const bool & info = false, const double & alpha = ALPHA, const char * master_key = "objects", const char * node_key = "url", const char * nn_key = "urls")
Constructor of PageRank object from json.
Parameters
json_path The input json filename
info Stdout informations, default: false
alpha Dumping factor, default: ALPHA
master_key Master key, default: objects
node_key Node key, default: url
nn_key Neighbors node key, default: urls
Definition at line 64 of file pagerank.cpp.
Member Function Documentation
csvRank()
void PageRank::csvRank (const char * out_path, const bool & info = false)
Write to csv rank result vector (_rank)
Parameters
out_path Output path to save results
info Stdout informations, default: false
Definition at line 119 of file pagerank.cpp.
evoRank() [1/2]
void PageRank::evoRank (const double & alpha, const double & epsilon = EPSILON, const bool & info = false)
Evolve pagerank of _sm with _alpha, and store result in _rank.
Parameters
alpha Dumping factor
epsilon Epsilon convergence error, default: EPSILON
info Stdout informations, default: false
Definition at line 173 of file pagerank.cpp.
References evoRank(), and setAlpha().
evoRank() [2/2]
void PageRank::evoRank (const double & epsilon = EPSILON, const bool & info = false)
Evolve pagerank of _am with _alpha, and store result in _rank.
Parameters
epsilon Epsilon convergence error, default: EPSILON
info Stdout informations, default: false
Definition at line 139 of file pagerank.cpp.
Referenced by evoRank().
getAdjMatrix()
arma::sp_mat PageRank::getAdjMatrix ()
Get arma adjacency matrix.
Returns
Armadillo adjacency matrix (_am)
Definition at line 98 of file pagerank.cpp.
getAlpha()
double PageRank::getAlpha ()
Get current dumping factor.
Returns
(_alpha) current dumping factor
Definition at line 91 of file pagerank.cpp.
getDangVec()
arma::vec PageRank::getDangVec ()
Get arma dangling nodes vector.
Returns
Armadillo dangling vector (_dang)
Definition at line 105 of file pagerank.cpp.
getRank()
arma::vec PageRank::getRank ()
Get arma rank result vector.
Returns
Armadillo rank result vector (_rank)
Definition at line 112 of file pagerank.cpp.
setAlpha()
void PageRank::setAlpha (const double & alpha)
Set dumping factor (_alpha)
Parameters
alpha Dumping factor
Definition at line 80 of file pagerank.cpp.
Referenced by evoRank(), and PageRank().
The documentation for this class was generated from the following files:
include/pagerank/pagerank.hpp
src/pagerank/pagerank.cpp