pgrank: include/json2mat/json2mat.hpp File Reference
json2mat.hpp File Reference
#include <armadillo>
#include <rapidjson/document.h>
#include <rapidjson/istreamwrapper.h>
Functions
rapidjson::Document _parseJson (const char *)
From json file to rapidjson document object.
std::unordered_map< std::string, unsigned int > _uMapJson (const char *, const bool &=false, const char *="objects", const char *="url")
From json file to unordered_map (string->uint), mapping needed to populate adjacency matrix.
std::pair< arma::sp_mat, arma::rowvec > adjacencyMatrixJson (const char *, const bool &=false, const char *="objects", const char *="url", const char *="urls")
Create normal adjacency matrix and dangling vector from json file.
Detailed Description
Authors
Andrea Rossoni
Version
0.1.3
Description
Library to parse json files and convert, them into armadillo adjacency matrix
WARNING json file must be something like:
{
   "master_key":
      [
         {
            "node_key": "node1",
            "nn_key": ["node3", "..."]
         },
         {
            "node_key": "node3",
            "nn_key": []
         },
         {
            ...
            ...
         },
      ]
}
So at master_key a list of dict, each with a node name (type: string) at node_key and its first neighbors nodes (type: list string) at nn_key
Also, all nn_nodes themselves must appear as nodes, at most they will not present any links (dangling nodes) but they must be present to make the graph consistent
Definition in file json2mat.hpp.
Function Documentation
_parseJson()
rapidjson::Document _parseJson (const char * json_path)
From json file to rapidjson document object.
Parameters
json_path The input json filename
Returns
Rapidjson document object containing parsed json
Authors
Andrea Rossoni
Version
0.1.3
Definition at line 11 of file json2mat.cpp.
Referenced by _uMapJson(), and adjacencyMatrixJson().
_uMapJson()
std::unordered_map<std::string, unsigned int> _uMapJson (const char * json_path, const bool & info = false, const char * master_key = "objects", const char * node_key = "url")
From json file to unordered_map (string->uint), mapping needed to populate adjacency matrix.
Parameters
json_path The input json filename
info Stdout informations, default: false
master_key Master key, default: objects
node_key Node key, default: url
Returns
Unordered map mapping node names from json to unsigned int
Definition at line 28 of file json2mat.cpp.
References _parseJson().
Referenced by adjacencyMatrixJson().
adjacencyMatrixJson()
std::pair<arma::sp_mat, arma::rowvec> adjacencyMatrixJson (const char * json_path, const bool & info = false, const char * master_key = "objects", const char * node_key = "url", const char * nn_key = "urls")
Create normal adjacency matrix and dangling vector from json file.
Parameters
json_path The input json filename
info Stdout informations, default: false
master_key Master key, default: objects
node_key Node key, default: url
nn_key Neighbors node key, default: urls
Returns
Adjacency matrix as armadillo spare matrix and dangling vector as armadillo rowvector
Definition at line 80 of file json2mat.cpp.
References _parseJson(), and _uMapJson().