---
name: JReleaser

"on":
  push:
    tags:
      - "v[0-9].[0-9].*"

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  issues: read
  packages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.ver.outputs.ver }}
    steps:
      - name: Get tag name
        id: ver
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Version: ${VERSION}"
          echo "##[set-output name=ver;]${VERSION}"
  release:
    name: JReleaser
    needs:
      - version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: JReleaser assemble
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.version.outputs.ver }}
      - name: Upload assemble logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-assemble
          retention-days: 1
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: JReleaser release
        uses: jreleaser/release-action@v2
        with:
          version: early-access
          arguments: release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ needs.version.outputs.ver }}
      - name: Upload release logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          retention-days: 1
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
  doxygen:
    name: Doxygen html
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.4.0
      - name: Download doxygen-awesome-css theme
        uses: robinraju/release-downloader@v1.3
        with:
          repository: "jothepro/doxygen-awesome-css"
          latest: true
          tarBall: true
          zipBall: false
          out-file-path: "."
      - name: Extract doxygen-awesome-css
        run: |
          tar xvf *.tar.gz
          rm -f *.tar.gz
          mv *doxygen-awesome-css* doxygen-awesome-css/
      - name: Create html docs
        uses: mattnotmitt/doxygen-action@v1.9.2
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
