---
name: JReleaser

"on":
  push:
    tags:
      - "v[0-9].[0-9].*"

jobs:
  version:
    name: Get version
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      ver: ${{ steps.ver.outputs.ver }}
    steps:
      - name: Get tag name
        id: ver
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "Version: ${VERSION}"
          echo "##[set-output name=ver;]${VERSION}"
  release:
    name: JReleaser
    needs:
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - name: JReleaser assemble
        uses: jreleaser/release-action@77fb95c777ffa93ba25e5218e233baafe16a731e
        with:
          version: early-access
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ needs.version.outputs.ver }}
      - name: Upload assemble logs
        if: always()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: jreleaser-assemble
          retention-days: 1
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
      - name: JReleaser release
        uses: jreleaser/release-action@77fb95c777ffa93ba25e5218e233baafe16a731e
        with:
          version: early-access
          arguments: release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ needs.version.outputs.ver }}
      - name: Upload release logs
        if: always()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: jreleaser-release
          retention-days: 1
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
  doxygen:
    name: Doxygen html
    needs:
      - release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout project
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Download doxygen-awesome-css theme
        uses: robinraju/release-downloader@ed86e52bc497d1185844fc28454c5999aaed2fa5
        with:
          repository: "jothepro/doxygen-awesome-css"
          latest: true
          tarBall: true
          zipBall: false
          out-file-path: "."
      - name: Extract doxygen-awesome-css
        run: |
          tar xvf *.tar.gz
          rm -f *.tar.gz
          mv *doxygen-awesome-css* doxygen-awesome-css/
      - name: Create html docs
        run: |
          sudo apt install doxygen
          doxygen
          sub=$(sed -n "/<a href=\"https:\/\/github.com\/andros21\/pgrank\">/,/<\/a>/p" README.md)
          sed -i "s|<a href=\"https://github.com/andros21/pgrank\">\(.*\)</a>|$(echo ${sub})|" html/index.html
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@b24891da2a683970a75ebe54633f084809cc25c0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html/
