---
name: Meson CI

"on":
  push:
    branches:
      - master
    paths:
      - 'meson.build'
      - 'meson_options.txt'
      - 'src/**'
      - 'subprojects/**'
      - 'tests/**'
  pull_request:
    branches:
      - master
    paths:
      - 'meson.build'
      - 'meson_options.txt'
      - 'src/**'
      - 'subprojects/**'
      - 'tests/**'

permissions:
  actions: read
  checks: read
  contents: read
  deployments: read
  issues: read
  packages: read
  pull-requests: write
  repository-projects: read
  security-events: read
  statuses: read

jobs:
  pre_ci:
    name: Prepare CI env
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
      repo: ${{ steps.repo.outputs.repo }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2.4.0
        with:
          # Fetch with a depth of 2 for pull_request so we can do HEAD^2
          fetch-depth: 2
      - name: Get branch name
        id: branch
        run: |
          TMP_PULL_HEAD_REF="${{ github.head_ref }}"
          TMP_GITHUB_REF="${GITHUB_REF#refs/heads/}"
          EXPORT_VALUE=""
          if [ "${TMP_PULL_HEAD_REF}" != "" ]
          then
              EXPORT_VALUE="${TMP_PULL_HEAD_REF}"
          else
              EXPORT_VALUE="${TMP_GITHUB_REF}"
          fi
          echo "Branch: ${EXPORT_VALUE}"
          echo "##[set-output name=branch;]${EXPORT_VALUE}"
      - name: Get repo name
        id: repo
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          echo "Repo: ${REPO_NAME}"
          echo "##[set-output name=repo;]${REPO_NAME}"
  meson:
    name: Meson Coverage
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v2.4.0
      - name: Install deps
        run: |
          sudo apt update
          sudo apt install libarmadillo-dev libopenblas-dev rapidjson-dev
          python -m pip install meson==0.59.0 ninja==1.10.0 gcovr==4.2
      - name: Create pkgconfig local dir
        run: mkdir -p "$HOME/.local/lib/pkgconfig"
      - name: Setup some envs
        run: |
          echo "HOME=$HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/.local/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig" >> $GITHUB_ENV
      # note: armadillo.pc not shipped by libarmadillo-devel
      - name: Create armadillo.pc
        run: |
          cat > $PKG_CONFIG_PATH/armadillo.pc << EOF
          libdir=/usr/include
          includedir=/usr/lib
          Name: armadillo
          Description: Fast C++ matrix library with syntax similar to MATLAB and Octave
          URL: http://arma.sourceforge.net
          Version: 9.800.4
          Cflags: -I${includedir}
          Libs: -L${libdir} -larmadillo
          EOF
      - name: Meson build and test
        run: |
          meson setup build --prefix $HOME/.local \
                            --libdir lib \
                            -Dtest=true \
                            -Db_coverage=true
          meson test -C build
      - name: Meson install
        run: meson install -C build
      - name: Run pgrank help
        run: pgrank --help
      - name: Check pgrank deps
        run: |
          pkg-config --cflags --libs json2mat
          pkg-config --cflags --libs pagerank
      - name: Meson coverage txt
        run: ninja coverage-text -C build
      - name: Meson coverage xml
        run: ninja coverage-xml -C build
      - name: Code coverage summary report
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          badge: true
          filename: build/meson-logs/coverage.xml
          format: 'markdown'
          hide_complexity: true
          output: both
      - name: Add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        if: ${{ github.event_name == 'pull_request' }}
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Report coverage
        if: ${{ github.event_name == 'push' }}
        id: coverage
        run: |
          COVERAGE=$(cat build/meson-logs/coverage.txt \
                      | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
          echo "##[set-output name=coverage;]${COVERAGE}"
  badge:
    name: Coverage Badge
    needs:
      - pre_ci
      - meson
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    env:
      gist_id: 0e20cd331d0800e3299298a3868aab7a
    outputs:
      markdown: ${{ steps.url.outputs.markdown }}
      url: ${{ steps.url.outputs.url }}
    steps:
      # note: Use the output from `coverage` id of `meson` job
      #       Use the output from `branch`, `repo` ids of `pre_ci` job
      - name: Generate dynamic badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          color: ${{
            needs.meson.outputs.coverage >  90 && 'brightgreen'   ||
            needs.meson.outputs.coverage >  80 && 'green'         ||
            needs.meson.outputs.coverage >  70 && 'yellowgreen'   ||
            needs.meson.outputs.coverage >  60 && 'yellow'        ||
            needs.meson.outputs.coverage >  50 && 'orange'        ||
            'red' }}
          filename: ${{ needs.pre_ci.outputs.repo }}__${{ needs.pre_ci.outputs.branch }}.json
          gistID: ${{ env.gist_id }}
          label: Coverage
          message: ${{ needs.meson.outputs.coverage }}%
          namedLogo: github
          style: flat-square
      - name: Badge image URL
        id: url
        run: |
          URL="https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/${{ github.actor }}/${{ env.gist_id }}/raw/${{ needs.pre_ci.outputs.repo }}__${{ needs.pre_ci.outputs.branch }}.json"
          MARKDOWN="![Coverage ${{ needs.meson.outputs.coverage }}](${URL})"
          echo "Badge URL: ${URL}"
          echo "Badge image for Markdown: ${MARKDOWN}"
          echo "##[set-output name=url;]${URL}"
          echo "##[set-output name=markdown;]${MARKDOWN}"
